### ISSUE TITLE
Broken after Instagram updated profiles.

### ISSUE THREAD

**Issue by andrewjburnett** [timgrossmann/instagram-profilecrawl#54] opened 2018-06-01 21:41 UTC
The error message is suppressed so I can't post the error beyond: 

$python crawl_profile.py john
Waiting 10 sec
Extracting information from john

Error: Couldn't get user profile.
Terminating

**Comment by justdvl** [comment] 2018-06-03 15:21
The problem is, the Chrome window doesn't even open, program doesn't even run anymore (for me)

**Comment by justdvl** [comment] 2018-06-04 15:54
I have done the fix 
https://github.com/timgrossmann/instagram-profilecrawl/pull/55

**Comment by timgrossmann** [comment] 2018-06-05 07:42
@andrewjburnett Please retry with the fix of @justdvl and close the issue if everything is working again.

**Comment by timmoh** [comment] 2018-06-28 09:50
works fine since a month

**Closed by timmoh** 2018-06-28 09:50 UTC
